In [1]:
import  numpy as np


In [3]:
a=np.array([[1,2,3,4],[3,1,2,4],[3,2,1,4]])

In [4]:
cal=a.sum(axis=0)

In [5]:
print(cal)

[ 7  5  6 12]


In [7]:
percentage=100*a/cal.reshape(1,4)

In [8]:
print(percentage)

[[14.28571429 40.         50.         33.33333333]
 [42.85714286 20.         33.33333333 33.33333333]
 [42.85714286 40.         16.66666667 33.33333333]]
