In [1]:
import numpy as np
a=np.random.randn(5)
#rank 1 array: dont use them.

In [2]:
a

array([ 1.2835579 ,  0.08268451, -0.45911216, -0.32762802, -0.77440864])

In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 1.2835579   0.08268451 -0.45911216 -0.32762802 -0.77440864]


In [6]:
print(np.dot(a,a.T))

2.5721904486880893


In [7]:
# right method
a=np.random.randn(5,1)

In [8]:
print(a.T)

[[ 2.19656409  0.90438383 -1.40734309  3.71037813 -0.49757913]]


In [9]:
print(a)

[[ 2.19656409]
 [ 0.90438383]
 [-1.40734309]
 [ 3.71037813]
 [-0.49757913]]


In [11]:
print(np.dot(a,a.T))

[[ 4.82489382  1.98653706 -3.09131929  8.15008339 -1.09296446]
 [ 1.98653706  0.81791012 -1.27277834  3.355606   -0.45000252]
 [-3.09131929 -1.27277834  1.98061456 -5.22177502  0.70026455]
 [ 8.15008339  3.355606   -5.22177502 13.7669059  -1.84620673]
 [-1.09296446 -0.45000252  0.70026455 -1.84620673  0.24758499]]


In [12]:
assert(a.shape==(5,1))